"""Book genres used to broaden a search when direct matches run out.

Each genre has a display label, an embedding description, exact-match terms,
and neighboring genres to try next. The order of neighbors is intentional.
"""

GENRES = {
    'self_development': {
        'label': 'Self-development',
        'profile': 'Personal growth, habits, motivation, productivity, discipline, goals, confidence, and success.',
        'terms': ['self-development', 'personal growth', 'habits', 'motivation', 'productivity'],
        'neighbors': [
            'psychology',
            'business_entrepreneurship',
            'health_wellness',
            'education_learning',
            'family_parenting',
        ],
    },
    'business_entrepreneurship': {
        'label': 'Business and entrepreneurship',
        'profile': 'Business, entrepreneurship, startups, leadership, management, marketing, sales, strategy, and building companies.',
        'terms': ['business', 'entrepreneurship', 'startup', 'leadership', 'marketing'],
        'neighbors': [
            'finance_investing',
            'self_development',
            'economics',
            'psychology',
            'technology_future',
        ],
    },
    'finance_investing': {
        'label': 'Finance and investing',
        'profile': 'Personal finance, money, investing, stocks, wealth, banking, budgeting, and financial freedom.',
        'terms': ['finance', 'money', 'investing', 'stocks', 'budget'],
        'neighbors': [
            'business_entrepreneurship',
            'economics',
            'self_development',
            'politics_society',
            'technology_future',
        ],
    },
    'economics': {
        'label': 'Economics',
        'profile': 'Economics, markets, trade, inequality, capitalism, labor, public policy, and economic history.',
        'terms': ['economics', 'markets', 'trade', 'inequality', 'capitalism'],
        'neighbors': [
            'finance_investing',
            'politics_society',
            'business_entrepreneurship',
            'history',
            'law_social_justice',
        ],
    },
    'politics_society': {
        'label': 'Politics and society',
        'profile': 'Politics, government, democracy, power, ideology, society, geopolitics, and public affairs.',
        'terms': ['politics', 'government', 'democracy', 'society', 'geopolitics'],
        'neighbors': [
            'history',
            'law_social_justice',
            'economics',
            'war_military',
            'essays_journalism',
        ],
    },
    'law_social_justice': {
        'label': 'Law and social justice',
        'profile': 'Law, justice, human rights, equality, discrimination, courts, crime, and social reform.',
        'terms': ['law', 'justice', 'human rights', 'equality', 'court'],
        'neighbors': [
            'politics_society',
            'crime_detective',
            'history',
            'economics',
            'essays_journalism',
        ],
    },
    'religion_spirituality': {
        'label': 'Religion and spirituality',
        'profile': 'Religion, faith, spirituality, sacred texts, ethics, worship, and the meaning of life.',
        'terms': ['religion', 'faith', 'spirituality', 'sacred texts', 'worship'],
        'neighbors': [
            'philosophy',
            'history',
            'mythology_legends',
            'psychology',
            'poetry',
        ],
    },
    'romance': {
        'label': 'Romance',
        'profile': 'Romance novels about love, relationships, marriage, heartbreak, intimacy, and finding a partner.',
        'terms': ['romance', 'love story', 'relationships', 'marriage', 'heartbreak'],
        'neighbors': [
            'contemporary_fiction',
            'literary_fiction',
            'drama',
            'historical_fiction',
            'poetry',
        ],
    },
    'fairy_tales_folklore': {
        'label': 'Fairy tales and folklore',
        'profile': 'Fairy tales, folk tales, fables, magical stories, legends, and traditional heroes.',
        'terms': ['fairy tale', 'folk tale', 'folklore', 'fable', 'legend'],
        'neighbors': [
            'mythology_legends',
            'children_young_adult',
            'fantasy',
            'adventure',
            'world_classics',
        ],
    },
    'mythology_legends': {
        'label': 'Mythology and legends',
        'profile': 'Mythology, ancient gods, heroes, epics, legends, creation stories, and traditional beliefs.',
        'terms': ['mythology', 'myth', 'gods', 'epic', 'legend'],
        'neighbors': [
            'fairy_tales_folklore',
            'fantasy',
            'religion_spirituality',
            'history',
            'adventure',
        ],
    },
    'world_classics': {
        'label': 'World classics',
        'profile': 'Classic world literature, famous authors, enduring novels, canonical works, and literary heritage.',
        'terms': ['world classics', 'classic literature', 'classics', 'canonical', 'literary heritage'],
        'neighbors': [
            'literary_fiction',
            'historical_fiction',
            'philosophy',
            'drama',
            'poetry',
        ],
    },
    'literary_fiction': {
        'label': 'Literary fiction',
        'profile': 'Literary fiction with rich language, complex characters, inner life, social themes, and artistic storytelling.',
        'terms': ['literary fiction', 'literature', 'novel', 'complex characters', 'artistic storytelling'],
        'neighbors': [
            'world_classics',
            'contemporary_fiction',
            'historical_fiction',
            'psychology',
            'philosophy',
        ],
    },
    'contemporary_fiction': {
        'label': 'Contemporary fiction',
        'profile': 'Modern fiction about present-day life, relationships, family, identity, work, and social change.',
        'terms': ['contemporary fiction', 'modern novel', 'present-day', 'identity', 'social change'],
        'neighbors': [
            'literary_fiction',
            'romance',
            'family_parenting',
            'psychology',
            'humor_satire',
        ],
    },
    'historical_fiction': {
        'label': 'Historical fiction',
        'profile': 'Historical novels set in past eras that mix fictional characters with real events, rulers, wars, and cultures.',
        'terms': ['historical fiction', 'historical novel', 'past era', 'historical characters', 'period novel'],
        'neighbors': [
            'history',
            'world_classics',
            'war_military',
            'adventure',
            'literary_fiction',
        ],
    },
    'history': {
        'label': 'History',
        'profile': 'History, civilizations, empires, nations, historical events, rulers, revolutions, and cultural change.',
        'terms': ['history', 'civilization', 'empire', 'historical events', 'revolution'],
        'neighbors': [
            'historical_fiction',
            'politics_society',
            'war_military',
            'biography_memoir',
            'travel_geography',
        ],
    },
    'philosophy': {
        'label': 'Philosophy',
        'profile': 'Philosophy, ethics, existence, knowledge, logic, freedom, morality, truth, and the meaning of life.',
        'terms': ['philosophy', 'ethics', 'existence', 'logic', 'morality'],
        'neighbors': [
            'psychology',
            'religion_spirituality',
            'literary_fiction',
            'world_classics',
            'science_nature',
        ],
    },
    'psychology': {
        'label': 'Psychology',
        'profile': 'Psychology, human behavior, emotions, the mind, trauma, personality, therapy, and mental health.',
        'terms': ['psychology', 'behavior', 'emotions', 'mind', 'therapy'],
        'neighbors': [
            'self_development',
            'philosophy',
            'health_wellness',
            'family_parenting',
            'literary_fiction',
        ],
    },
    'fantasy': {
        'label': 'Fantasy',
        'profile': 'Fantasy worlds, magic, quests, imaginary kingdoms, supernatural creatures, heroes, and epic adventures.',
        'terms': ['fantasy', 'magic', 'quest', 'imaginary kingdom', 'epic fantasy'],
        'neighbors': [
            'mythology_legends',
            'science_fiction',
            'adventure',
            'fairy_tales_folklore',
            'horror_gothic',
        ],
    },
    'science_fiction': {
        'label': 'Science fiction',
        'profile': 'Science fiction about space, aliens, future societies, technology, robots, time travel, and scientific possibilities.',
        'terms': ['science fiction', 'space', 'aliens', 'future', 'robots'],
        'neighbors': [
            'technology_future',
            'dystopian',
            'fantasy',
            'science_nature',
            'adventure',
        ],
    },
    'dystopian': {
        'label': 'Dystopian fiction',
        'profile': 'Dystopian fiction about authoritarian rule, surveillance, social control, collapse, resistance, and dark futures.',
        'terms': ['dystopian', 'dystopia', 'authoritarian', 'surveillance', 'resistance'],
        'neighbors': [
            'science_fiction',
            'politics_society',
            'war_military',
            'horror_gothic',
            'technology_future',
        ],
    },
    'mystery_thriller': {
        'label': 'Mystery and thriller',
        'profile': 'Mystery, suspense, secrets, danger, investigations, conspiracies, and tense page-turning stories.',
        'terms': ['mystery', 'thriller', 'suspense', 'investigation', 'conspiracy'],
        'neighbors': [
            'crime_detective',
            'horror_gothic',
            'adventure',
            'psychology',
            'dystopian',
        ],
    },
    'crime_detective': {
        'label': 'Crime and detective',
        'profile': 'Crime fiction, detectives, murder cases, police investigations, criminals, courtroom cases, and clues.',
        'terms': ['crime', 'detective', 'murder', 'police', 'criminal'],
        'neighbors': [
            'mystery_thriller',
            'law_social_justice',
            'psychology',
            'horror_gothic',
            'adventure',
        ],
    },
    'horror_gothic': {
        'label': 'Horror and gothic',
        'profile': 'Horror, gothic fiction, fear, ghosts, monsters, haunted places, darkness, and supernatural terror.',
        'terms': ['horror', 'gothic', 'ghost', 'monster', 'haunted'],
        'neighbors': [
            'mystery_thriller',
            'fantasy',
            'crime_detective',
            'dystopian',
            'mythology_legends',
        ],
    },
    'adventure': {
        'label': 'Adventure',
        'profile': 'Adventure stories about journeys, exploration, survival, danger, treasure, heroes, and unknown places.',
        'terms': ['adventure', 'journey', 'exploration', 'survival', 'treasure'],
        'neighbors': [
            'travel_geography',
            'fantasy',
            'historical_fiction',
            'science_fiction',
            'children_young_adult',
        ],
    },
    'biography_memoir': {
        'label': 'Biography and memoir',
        'profile': 'Biographies, memoirs, autobiographies, real lives, personal journeys, leaders, artists, and historical figures.',
        'terms': ['biography', 'memoir', 'autobiography', 'life story', 'historical figure'],
        'neighbors': [
            'history',
            'self_development',
            'essays_journalism',
            'politics_society',
            'culture_art',
        ],
    },
    'poetry': {
        'label': 'Poetry',
        'profile': 'Poetry, poems, lyrical writing, love poems, nature poems, spiritual verse, and poetic collections.',
        'terms': ['poetry', 'poem', 'verse', 'lyric', 'poetic collection'],
        'neighbors': [
            'drama',
            'romance',
            'literary_fiction',
            'religion_spirituality',
            'world_classics',
        ],
    },
    'drama': {
        'label': 'Drama',
        'profile': 'Drama, plays, tragedy, comedy, stage works, family conflict, and intense human relationships.',
        'terms': ['drama', 'play', 'tragedy', 'comedy', 'theatre'],
        'neighbors': [
            'literary_fiction',
            'world_classics',
            'romance',
            'poetry',
            'humor_satire',
        ],
    },
    'children_young_adult': {
        'label': 'Children and young adult',
        'profile': "Children's books and young-adult stories about growing up, school, friendship, family, imagination, and first challenges.",
        'terms': ["children's books", 'young adult', 'school', 'growing up', 'friendship'],
        'neighbors': [
            'fairy_tales_folklore',
            'adventure',
            'family_parenting',
            'fantasy',
            'education_learning',
        ],
    },
    'family_parenting': {
        'label': 'Family and parenting',
        'profile': 'Family, parenting, marriage, raising children, communication, home life, and healthy relationships.',
        'terms': ['family', 'parenting', 'marriage', 'raising children', 'communication'],
        'neighbors': [
            'psychology',
            'children_young_adult',
            'health_wellness',
            'self_development',
            'romance',
        ],
    },
    'education_learning': {
        'label': 'Education and learning',
        'profile': 'Education, teaching, learning, study skills, schools, teachers, memory, and intellectual development.',
        'terms': ['education', 'teaching', 'learning', 'study', 'teacher'],
        'neighbors': [
            'self_development',
            'children_young_adult',
            'psychology',
            'science_nature',
            'technology_future',
        ],
    },
    'science_nature': {
        'label': 'Science and nature',
        'profile': 'Popular science, physics, biology, astronomy, evolution, animals, the environment, and nature.',
        'terms': ['science', 'physics', 'biology', 'astronomy', 'nature'],
        'neighbors': [
            'technology_future',
            'science_fiction',
            'health_wellness',
            'education_learning',
            'travel_geography',
        ],
    },
    'health_wellness': {
        'label': 'Health and wellness',
        'profile': 'Health, medicine, fitness, nutrition, sleep, mindfulness, mental wellbeing, and healthy living.',
        'terms': ['health', 'medicine', 'fitness', 'nutrition', 'wellbeing'],
        'neighbors': [
            'psychology',
            'self_development',
            'science_nature',
            'family_parenting',
            'cooking_lifestyle',
        ],
    },
    'culture_art': {
        'label': 'Culture and art',
        'profile': 'Art, culture, painting, music, cinema, architecture, creativity, artists, and cultural criticism.',
        'terms': ['art', 'culture', 'painting', 'music', 'cinema'],
        'neighbors': [
            'literary_fiction',
            'biography_memoir',
            'poetry',
            'history',
            'essays_journalism',
        ],
    },
    'humor_satire': {
        'label': 'Humor and satire',
        'profile': 'Humor, satire, witty stories, social comedy, parody, absurdity, and books written to amuse or criticize.',
        'terms': ['humor', 'satire', 'comedy', 'parody', 'absurd'],
        'neighbors': [
            'drama',
            'contemporary_fiction',
            'essays_journalism',
            'politics_society',
            'children_young_adult',
        ],
    },
    'war_military': {
        'label': 'War and military',
        'profile': 'War, military history, soldiers, battles, strategy, conflict, survival, and the human cost of war.',
        'terms': ['war', 'military', 'soldier', 'battle', 'strategy'],
        'neighbors': [
            'history',
            'historical_fiction',
            'politics_society',
            'adventure',
            'biography_memoir',
        ],
    },
    'travel_geography': {
        'label': 'Travel and geography',
        'profile': 'Travel writing, countries, cities, geography, cultures, exploration, journeys, and life abroad.',
        'terms': ['travel', 'geography', 'countries', 'cities', 'exploration'],
        'neighbors': [
            'adventure',
            'history',
            'culture_art',
            'biography_memoir',
            'science_nature',
        ],
    },
    'essays_journalism': {
        'label': 'Essays and journalism',
        'profile': 'Essays, journalism, reportage, commentary, social criticism, current affairs, and thoughtful nonfiction.',
        'terms': ['essay', 'journalism', 'reportage', 'commentary', 'nonfiction'],
        'neighbors': [
            'politics_society',
            'biography_memoir',
            'law_social_justice',
            'culture_art',
            'history',
        ],
    },
    'technology_future': {
        'label': 'Technology and the future',
        'profile': 'Technology, computers, artificial intelligence, the internet, innovation, digital society, and the future of work.',
        'terms': ['technology', 'computers', 'artificial intelligence', 'internet', 'innovation'],
        'neighbors': [
            'science_nature',
            'science_fiction',
            'business_entrepreneurship',
            'education_learning',
            'dystopian',
        ],
    },
    'cooking_lifestyle': {
        'label': 'Cooking and lifestyle',
        'profile': 'Cooking, recipes, food culture, home, everyday lifestyle, hospitality, crafts, and practical living.',
        'terms': ['cooking', 'recipes', 'food', 'lifestyle', 'hospitality'],
        'neighbors': [
            'health_wellness',
            'family_parenting',
            'culture_art',
            'travel_geography',
            'self_development',
        ],
    },
    'sports': {
        'label': 'Sports',
        'profile': 'Sports, athletes, football, competition, coaching, teamwork, training, performance, and sporting biographies.',
        'terms': ['sports', 'athlete', 'football', 'competition', 'coaching'],
        'neighbors': [
            'health_wellness',
            'biography_memoir',
            'self_development',
            'business_entrepreneurship',
            'children_young_adult',
        ],
    },
}

GENERAL_BOOK_PROFILE = 'Books and reading in every genre: novels, useful nonfiction, reviews, thoughtful recommendations, literature, stories, and authors.'
GENERAL_BOOK_TERMS = ['book', 'books', 'reading', 'literature', 'novel', 'review']
