"""English-language book-interest genres and their nearest neighbors."""


def _genre(label: str, profile: str, terms: list[str], neighbors: list[str]) -> dict[str, object]:
    return {"label": label, "profile": profile, "terms": terms, "neighbors": neighbors}


GENRES = {
    "self_development": _genre("Self-development", "Personal growth, habits, motivation, productivity, discipline, goals, confidence, and success.", ["self-development", "personal growth", "habits", "motivation", "productivity"], ["psychology", "business_entrepreneurship", "health_wellness", "education_learning", "family_parenting"]),
    "business_entrepreneurship": _genre("Business and entrepreneurship", "Business, entrepreneurship, startups, leadership, management, marketing, sales, strategy, and building companies.", ["business", "entrepreneurship", "startup", "leadership", "marketing"], ["finance_investing", "self_development", "economics", "psychology", "technology_future"]),
    "finance_investing": _genre("Finance and investing", "Personal finance, money, investing, stocks, wealth, banking, budgeting, and financial freedom.", ["finance", "money", "investing", "stocks", "budget"], ["business_entrepreneurship", "economics", "self_development", "politics_society", "technology_future"]),
    "economics": _genre("Economics", "Economics, markets, trade, inequality, capitalism, labor, public policy, and economic history.", ["economics", "markets", "trade", "inequality", "capitalism"], ["finance_investing", "politics_society", "business_entrepreneurship", "history", "law_social_justice"]),
    "politics_society": _genre("Politics and society", "Politics, government, democracy, power, ideology, society, geopolitics, and public affairs.", ["politics", "government", "democracy", "society", "geopolitics"], ["history", "law_social_justice", "economics", "war_military", "essays_journalism"]),
    "law_social_justice": _genre("Law and social justice", "Law, justice, human rights, equality, discrimination, courts, crime, and social reform.", ["law", "justice", "human rights", "equality", "court"], ["politics_society", "crime_detective", "history", "economics", "essays_journalism"]),
    "religion_spirituality": _genre("Religion and spirituality", "Religion, faith, spirituality, sacred texts, ethics, worship, and the meaning of life.", ["religion", "faith", "spirituality", "sacred texts", "worship"], ["philosophy", "history", "mythology_legends", "psychology", "poetry"]),
    "romance": _genre("Romance", "Romance novels about love, relationships, marriage, heartbreak, intimacy, and finding a partner.", ["romance", "love story", "relationships", "marriage", "heartbreak"], ["contemporary_fiction", "literary_fiction", "drama", "historical_fiction", "poetry"]),
    "fairy_tales_folklore": _genre("Fairy tales and folklore", "Fairy tales, folk tales, fables, magical stories, legends, and traditional heroes.", ["fairy tale", "folk tale", "folklore", "fable", "legend"], ["mythology_legends", "children_young_adult", "fantasy", "adventure", "world_classics"]),
    "mythology_legends": _genre("Mythology and legends", "Mythology, ancient gods, heroes, epics, legends, creation stories, and traditional beliefs.", ["mythology", "myth", "gods", "epic", "legend"], ["fairy_tales_folklore", "fantasy", "religion_spirituality", "history", "adventure"]),
    "world_classics": _genre("World classics", "Classic world literature, famous authors, enduring novels, canonical works, and literary heritage.", ["world classics", "classic literature", "classics", "canonical", "literary heritage"], ["literary_fiction", "historical_fiction", "philosophy", "drama", "poetry"]),
    "literary_fiction": _genre("Literary fiction", "Literary fiction with rich language, complex characters, inner life, social themes, and artistic storytelling.", ["literary fiction", "literature", "novel", "complex characters", "artistic storytelling"], ["world_classics", "contemporary_fiction", "historical_fiction", "psychology", "philosophy"]),
    "contemporary_fiction": _genre("Contemporary fiction", "Modern fiction about present-day life, relationships, family, identity, work, and social change.", ["contemporary fiction", "modern novel", "present-day", "identity", "social change"], ["literary_fiction", "romance", "family_parenting", "psychology", "humor_satire"]),
    "historical_fiction": _genre("Historical fiction", "Historical novels set in past eras that mix fictional characters with real events, rulers, wars, and cultures.", ["historical fiction", "historical novel", "past era", "historical characters", "period novel"], ["history", "world_classics", "war_military", "adventure", "literary_fiction"]),
    "history": _genre("History", "History, civilizations, empires, nations, historical events, rulers, revolutions, and cultural change.", ["history", "civilization", "empire", "historical events", "revolution"], ["historical_fiction", "politics_society", "war_military", "biography_memoir", "travel_geography"]),
    "philosophy": _genre("Philosophy", "Philosophy, ethics, existence, knowledge, logic, freedom, morality, truth, and the meaning of life.", ["philosophy", "ethics", "existence", "logic", "morality"], ["psychology", "religion_spirituality", "literary_fiction", "world_classics", "science_nature"]),
    "psychology": _genre("Psychology", "Psychology, human behavior, emotions, the mind, trauma, personality, therapy, and mental health.", ["psychology", "behavior", "emotions", "mind", "therapy"], ["self_development", "philosophy", "health_wellness", "family_parenting", "literary_fiction"]),
    "fantasy": _genre("Fantasy", "Fantasy worlds, magic, quests, imaginary kingdoms, supernatural creatures, heroes, and epic adventures.", ["fantasy", "magic", "quest", "imaginary kingdom", "epic fantasy"], ["mythology_legends", "science_fiction", "adventure", "fairy_tales_folklore", "horror_gothic"]),
    "science_fiction": _genre("Science fiction", "Science fiction about space, aliens, future societies, technology, robots, time travel, and scientific possibilities.", ["science fiction", "space", "aliens", "future", "robots"], ["technology_future", "dystopian", "fantasy", "science_nature", "adventure"]),
    "dystopian": _genre("Dystopian fiction", "Dystopian fiction about authoritarian rule, surveillance, social control, collapse, resistance, and dark futures.", ["dystopian", "dystopia", "authoritarian", "surveillance", "resistance"], ["science_fiction", "politics_society", "war_military", "horror_gothic", "technology_future"]),
    "mystery_thriller": _genre("Mystery and thriller", "Mystery, suspense, secrets, danger, investigations, conspiracies, and tense page-turning stories.", ["mystery", "thriller", "suspense", "investigation", "conspiracy"], ["crime_detective", "horror_gothic", "adventure", "psychology", "dystopian"]),
    "crime_detective": _genre("Crime and detective", "Crime fiction, detectives, murder cases, police investigations, criminals, courtroom cases, and clues.", ["crime", "detective", "murder", "police", "criminal"], ["mystery_thriller", "law_social_justice", "psychology", "horror_gothic", "adventure"]),
    "horror_gothic": _genre("Horror and gothic", "Horror, gothic fiction, fear, ghosts, monsters, haunted places, darkness, and supernatural terror.", ["horror", "gothic", "ghost", "monster", "haunted"], ["mystery_thriller", "fantasy", "crime_detective", "dystopian", "mythology_legends"]),
    "adventure": _genre("Adventure", "Adventure stories about journeys, exploration, survival, danger, treasure, heroes, and unknown places.", ["adventure", "journey", "exploration", "survival", "treasure"], ["travel_geography", "fantasy", "historical_fiction", "science_fiction", "children_young_adult"]),
    "biography_memoir": _genre("Biography and memoir", "Biographies, memoirs, autobiographies, real lives, personal journeys, leaders, artists, and historical figures.", ["biography", "memoir", "autobiography", "life story", "historical figure"], ["history", "self_development", "essays_journalism", "politics_society", "culture_art"]),
    "poetry": _genre("Poetry", "Poetry, poems, lyrical writing, love poems, nature poems, spiritual verse, and poetic collections.", ["poetry", "poem", "verse", "lyric", "poetic collection"], ["drama", "romance", "literary_fiction", "religion_spirituality", "world_classics"]),
    "drama": _genre("Drama", "Drama, plays, tragedy, comedy, stage works, family conflict, and intense human relationships.", ["drama", "play", "tragedy", "comedy", "theatre"], ["literary_fiction", "world_classics", "romance", "poetry", "humor_satire"]),
    "children_young_adult": _genre("Children and young adult", "Children's books and young-adult stories about growing up, school, friendship, family, imagination, and first challenges.", ["children's books", "young adult", "school", "growing up", "friendship"], ["fairy_tales_folklore", "adventure", "family_parenting", "fantasy", "education_learning"]),
    "family_parenting": _genre("Family and parenting", "Family, parenting, marriage, raising children, communication, home life, and healthy relationships.", ["family", "parenting", "marriage", "raising children", "communication"], ["psychology", "children_young_adult", "health_wellness", "self_development", "romance"]),
    "education_learning": _genre("Education and learning", "Education, teaching, learning, study skills, schools, teachers, memory, and intellectual development.", ["education", "teaching", "learning", "study", "teacher"], ["self_development", "children_young_adult", "psychology", "science_nature", "technology_future"]),
    "science_nature": _genre("Science and nature", "Popular science, physics, biology, astronomy, evolution, animals, the environment, and nature.", ["science", "physics", "biology", "astronomy", "nature"], ["technology_future", "science_fiction", "health_wellness", "education_learning", "travel_geography"]),
    "health_wellness": _genre("Health and wellness", "Health, medicine, fitness, nutrition, sleep, mindfulness, mental wellbeing, and healthy living.", ["health", "medicine", "fitness", "nutrition", "wellbeing"], ["psychology", "self_development", "science_nature", "family_parenting", "cooking_lifestyle"]),
    "culture_art": _genre("Culture and art", "Art, culture, painting, music, cinema, architecture, creativity, artists, and cultural criticism.", ["art", "culture", "painting", "music", "cinema"], ["literary_fiction", "biography_memoir", "poetry", "history", "essays_journalism"]),
    "humor_satire": _genre("Humor and satire", "Humor, satire, witty stories, social comedy, parody, absurdity, and books written to amuse or criticize.", ["humor", "satire", "comedy", "parody", "absurd"], ["drama", "contemporary_fiction", "essays_journalism", "politics_society", "children_young_adult"]),
    "war_military": _genre("War and military", "War, military history, soldiers, battles, strategy, conflict, survival, and the human cost of war.", ["war", "military", "soldier", "battle", "strategy"], ["history", "historical_fiction", "politics_society", "adventure", "biography_memoir"]),
    "travel_geography": _genre("Travel and geography", "Travel writing, countries, cities, geography, cultures, exploration, journeys, and life abroad.", ["travel", "geography", "countries", "cities", "exploration"], ["adventure", "history", "culture_art", "biography_memoir", "science_nature"]),
    "essays_journalism": _genre("Essays and journalism", "Essays, journalism, reportage, commentary, social criticism, current affairs, and thoughtful nonfiction.", ["essay", "journalism", "reportage", "commentary", "nonfiction"], ["politics_society", "biography_memoir", "law_social_justice", "culture_art", "history"]),
    "technology_future": _genre("Technology and the future", "Technology, computers, artificial intelligence, the internet, innovation, digital society, and the future of work.", ["technology", "computers", "artificial intelligence", "internet", "innovation"], ["science_nature", "science_fiction", "business_entrepreneurship", "education_learning", "dystopian"]),
    "cooking_lifestyle": _genre("Cooking and lifestyle", "Cooking, recipes, food culture, home, everyday lifestyle, hospitality, crafts, and practical living.", ["cooking", "recipes", "food", "lifestyle", "hospitality"], ["health_wellness", "family_parenting", "culture_art", "travel_geography", "self_development"]),
    "sports": _genre("Sports", "Sports, athletes, football, competition, coaching, teamwork, training, performance, and sporting biographies.", ["sports", "athlete", "football", "competition", "coaching"], ["health_wellness", "biography_memoir", "self_development", "business_entrepreneurship", "children_young_adult"]),
}

GENERAL_BOOK_PROFILE = "Books and reading in every genre: novels, useful nonfiction, reviews, thoughtful recommendations, literature, stories, and authors."
GENERAL_BOOK_TERMS = ["book", "books", "reading", "literature", "novel", "review"]
